##################################################################################################
# HPML-J                                                                                         #
# Hybrid Partitions for Multi-label Classification version Jaccard                               #
# Copyright (C) 2021                                                                             #
#                                                                                                #
# This program is free software: you can redistribute it and/or modify it under the terms of the #
# GNU General Public License as published by the Free Software Foundation, either version 3 of   #  
# the License, or (at your option) any later version. This program is distributed in the hope    #
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for    #
# more details.                                                                                  #     
#                                                                                                #
# Elaine Cecilia Gatto | Prof. Dr. Ricardo Cerri | Prof. Dr. Mauri Ferrandin                     #
# Federal University of Sao Carlos (UFSCar: https://www2.ufscar.br/) Campus Sao Carlos           #
# Computer Department (DC: https://site.dc.ufscar.br/)                                           #
# Program of Post Graduation in Computer Science (PPG-CC: http://ppgcc.dc.ufscar.br/)            #
# Bioinformatics and Machine Learning Group (BIOMAL: http://www.biomal.ufscar.br/)               #
#                                                                                                #
##################################################################################################

##################################################################################################
# Script 6 - Partitions                                                                          #
##################################################################################################

##################################################################################################
# Workspace configuration                                                                        #
##################################################################################################
sf = setFolder()
setwd(sf$Folder)
FolderRoot = sf$Folder
diretorios = directories()


##################################################################################################
# FUNCTION HYBRID PARTITIONS                                                                     #
#   Objective                                                                                    #
#       Generate the arff files for validation and training, of the hybrid partitions, to run    # 
#       in the clus.                                                                               # 
#   Parameters                                                                                   #
#       ds: specific dataset information                                                         #
#       dataset_name: dataset name. It is used to save files.                                    #
#       number_folds: number of folds created                                                    #
#       DsFolders:path of 10-folds cross validation                                              #
#       FolderHClust: path of files generated by HClust and Cutree                               #
#       FolderHybrid: path of hybrid partition results                                           #
#   Return                                                                                       #
#       files .arff                                                                              #
##################################################################################################
hybridPartitions <- function(ds, dataset_name, number_folds, DsFolders, FolderHClust, FolderHybPart){  
  
  dataset_name = dataset_name
  
  # set folder
  sf = setFolder()
  setwd(sf$Folder)
  FolderRoot = sf$Folder
  diretorios = directories()
  
  # Train folder
  FolderTr = paste(DsFolders, "/Tr", sep="")
  dirFolderTr = c(dir(FolderTr))
  n_dirFolderTr = length(dirFolderTr)
  
  # Validation Folder
  FolderVl = paste(DsFolders, "/Vl", sep="")
  dirFolderVl = c(dir(FolderVl))
  n_dirFolderVl = length(dirFolderVl)  
  
  gr = c(0)
  TodasParticoes = data.frame(gr)
  
  # fold 1 to number_folds
  f = 1  
  hybridParalel <- foreach(f = 1:number_folds) %dopar%{  
    
    cat("\n\tFold: ", f)   
    
    ############################################################################################################
    # cat("\nLOAD LIBRARY \n")
    library("stringr")
    library("AggregateR")    
    library("plyr")
    library("dplyr")
    library("mldr")
    library("utiml")
    library("foreign")
    
    ############################################################################################################
    # cat("\nSET WORKSPACE \n")
    sistema = c(Sys.info())
    FolderRoot = ""
    if (sistema[1] == "Linux"){
      FolderRoot = paste("/home/", sistema[7], "/HPML-J", sep="")
      setwd(FolderRoot)
    } else {
      FolderRoot = paste("C:/Users/", sistema[7], "/HPML-J", sep="")
      setwd(FolderRoot)
    }
    
    ############################################################################################################
    setwd(FolderRoot)
    folderUtils = paste(FolderRoot, "/utils", sep="")
    dataset_name = dataset_name    
    
    ############################################################################################################
    FolderScripts = paste(FolderRoot, "/scripts/", sep="")
    setwd(FolderScripts)
    
    ############################################################################################################
    #cat("\nLOAD FUNCTION REMOVE CSV \n")
    RemoveCSV <- function(filenames){
      folderNames = filenames
      j = 0
      for(j in 1:length(folderNames)){
        a = str_length(folderNames[j])
        a = a - 4
        folderNames[j] = str_sub(folderNames[j], end = a)  
        j = j + 1
        gc()
      }  
      return(folderNames)
    }
    
    ############################################################################################################
    #cat("\nLOAD FUNCTION CONVERT ARFF \n")
    converteArff <- function(arg1, arg2, arg3){
      str = paste("java -jar ", folderUtils, "/R_csv_2_arff.jar ", arg1, " ", arg2, " ", arg3, sep="")
      system(str)
      cat("\n\n")  
    }
    
    ############################################################################################################
    #cat("\nSELECT THE HIGHIEST COEFFICIENT \n")
    setwd(FolderHClust)
    coeficiente = data.frame(read.csv("BestFoldsCoef.csv"))
    coeficiente_fold = coeficiente[f,]
    metodo_fold = toString(coeficiente_fold$metodo)
    
    ############################################################################################################
    # creating folders
    FolderClusterSplit = paste(FolderHClust, "/Split-", f, sep="")
    FolderClusterSplitMethod = paste(FolderClusterSplit, "/", metodo_fold, "/Clusters", sep="")
    FolderHybPartSplit = paste(FolderHybPart, "/Split-", f, sep="")
    if(dir.exists(FolderHybPartSplit)==TRUE){
      #cat("\nFolder existe")
    } else {
      dir.create(FolderHybPartSplit)
    }
    
    ############################################################################################################
    #cat("\nSTART MOUNT PARTITIONS\n")
    num.part = ds$Labels-1
    
    # from the partition = 2 to partition = l-2
    p = 2
    while(p<=num.part){
      
      setwd(FolderRoot)
      folderUtils = paste(FolderRoot, "/utils", sep="")
      
      ####################################################################################
      library("foreign")
      dataset_name = dataset_name
      
      ####################################################################################
      nome_particao = paste("particao_", p, sep="")
      nome_particao_2 = paste("Partition-", p, sep="")
      cat("\n\t\tPartition: ", nome_particao)
      
      ####################################################################################
      nomeTr = paste(dataset_name, "-Split-Tr-", f, ".csv", sep="")
      nomeVl = paste(dataset_name, "-Split-Vl-", f, ".csv", sep="")   
      
      ####################################################################################
      #cat("\nSELECT THE CUTREE\n")
      setwd(FolderClusterSplitMethod)
      cluster = paste("cluster_", p, ".csv", sep="")
      particao2 = data.frame(read.csv(cluster, stringsAsFactors = F))
      names(particao2)[1] = "labels"
      particao = particao2[order(particao2$grupo, decreasing = FALSE),]
      numeroDeGrupos = count(particao, vars=particao$grupo)
      names(numeroDeGrupos) = c("grupos", "totalRotulos")
      totalGroupsPart = nrow(numeroDeGrupos)
      
      ####################################################################################
      FolderSplitPart = paste(FolderHybPartSplit, "/", nome_particao_2, sep="")
      if(dir.exists(FolderSplitPart)==TRUE){
        #cat("\nFolder Existe\n")
      } else {
        dir.create(FolderSplitPart)
      }
      
      ####################################################################################
      # if the group is equal to 1, do nothing
      # but if not, do:
      if(totalGroupsPart == 1){
        #cat("\nTOTAL GROUPS == 1\n")
      } else { 
        
        library("foreign")
        
        ####################################################################################
        #cat("\nTOTAL GROUPS < > 1\n")
        #cat("\nSTART MOUNT GROUPS OF LABELS FOR EACH PARTITION\n")
        # starts in the first cluster and goes to the last
        g = 1
        while(g<=totalGroupsPart){
          
          setwd(FolderRoot)
          folderUtils = paste(FolderRoot, "/utils", sep="")
          
          ####################################################################################
          library("foreign")
          dataset_name = dataset_name 
          
          ####################################################################################
          nome_grupo = paste("grupo_", g, sep="")           
          nome_grupo_2 = paste("Group-", g, sep="")
          cat("\n\t\tGroup: ", nome_grupo)
          
          ####################################################################################
          nomeTr = paste(dataset_name, "-Split-Tr-", f, ".csv", sep="")
          nomeVl = paste(dataset_name, "-Split-Vl-", f, ".csv", sep="")   
          
          ####################################################################################
          FolderSplitPartGroup = paste(FolderSplitPart , "/", nome_grupo_2, sep="")
          if(dir.exists(FolderSplitPartGroup)==TRUE){
            #cat("\nFolder Existe")
          } else {
            dir.create(FolderSplitPartGroup)  
          }
          
          ####################################################################################
          # get the labels of this group
          setwd(FolderSplitPartGroup)
          a = particao %>% filter(., particao$grupo == g)
          #cat("\nTotal of labels for this group: ", nrow(a), "\n")
          
          ####################################################################################
          # mount group
          nome_grupo = paste("grupo_", g, sep="")           
          grSpecThisPart = a
          totalLabelsThisGr = nrow(a)
          print(grSpecThisPart)
          
          ####################################################################################
          #cat("\nTRAIN: Get the original file\n")
          cat("\n\t\t\tCreating Train File")
          setwd(FolderTr)
          nomeTr2 = paste(FolderTr, "/", nomeTr, sep="")
          
          ####################################################################################
          #cat("\nTRAIN: MOUNT GROUP\n")
          arquivoTr = data.frame(read.csv(nomeTr2), stringsAsFactors = F)
          atributosTr = arquivoTr[ds$AttStart:ds$AttEnd]
          rotulosTr = toString(grSpecThisPart$labels)
          classesTr = select(arquivoTr, grSpecThisPart$labels)
          thisGroupTr = cbind(atributosTr, classesTr)
          
          ####################################################################################
          #cat("\nTRAIN: Save CSV\n")
          nomeCsTr = paste("grupo_Tr_", g, ".csv", sep="")
          nomeArTr = paste("grupo_Tr_", g, ".arff", sep="")
          setwd(FolderSplitPartGroup)
          write.csv(thisGroupTr, nomeCsTr, row.names = FALSE)
          
          ####################################################################################
          #cat("\nTRAIN: Start End Targets\n")
          inicio = ds$LabelStart
          fim = ncol(thisGroupTr)
          ifr = data.frame(inicio, fim)
          setwd(FolderSplitPartGroup)
          write.csv(ifr, "inicioFimRotulos.csv", row.names = FALSE)
          
          ####################################################################################
          #cat("\nTRAIN: Convert CSV to ARFF\n")
          setwd(FolderSplitPartGroup)
          arg1 = nomeCsTr
          arg2 = nomeArTr
          arg3 = paste(inicio, "-", fim, sep="")
          converteArff(arg1, arg2, arg3)
          
          ####################################################################################
          #cat("\nTRAIN: Verify and correct {0} and {1}\n")
          arquivo = paste(FolderSplitPartGroup, "/", nomeArTr, sep="")
          str0 = paste("sed -i 's/{0}/{0,1}/g;s/{1}/{0,1}/g' ", arquivo, sep="")
          system(str0)
          
          ####################################################################################
          #cat("\nVALIDATION: Get the file\n")
          cat("\n\t\t\tCreating Validation File")
          setwd(FolderVl)
          nomeVl2 = paste(FolderVl, "/", nomeVl, sep="")
          
          ####################################################################################
          #cat("\nVALIDATION: MOUNT GROUP\n")
          arquivoVl = data.frame(read.csv(nomeVl2), stringsAsFactors = F)
          atributosVl = arquivoVl[ds$AttStart:ds$AttEnd]
          rotulosVl = toString(grSpecThisPart$labels)
          classesVl = select(arquivoVl, grSpecThisPart$labels)
          thisGroupVl = cbind(atributosVl, classesVl)
          
          ####################################################################################
          #cat("\nVALIDATION: Save CSV\n")
          nomeCsVl = paste("grupo_Vl_", g, ".csv", sep="")
          nomeArVl = paste("grupo_Vl_", g, ".arff", sep="")
          setwd(FolderSplitPartGroup)
          write.csv(thisGroupVl, nomeCsVl, row.names = FALSE)
          
          ####################################################################################
          #cat("\nVALIDATION: Convert CSV to ARFF\n")
          setwd(FolderSplitPartGroup)
          arg1 = nomeCsVl
          arg2 = nomeArVl
          arg3 = paste(inicio, "-", fim, sep="")
          converteArff(arg1, arg2, arg3)
          
          ####################################################################################
          #cat("\nVALIDATION: Verify and correct {0} and {1}\n")
          arquivo = paste(FolderSplitPartGroup, "/", nomeArVl, sep="")
          str0 = paste("sed -i 's/{0}/{0,1}/g;s/{1}/{0,1}/g' ", arquivo, sep="")
          system(str0)
          
          ####################################################################################
          cat("\n\t\t\tCreating .s file for Clus")
          setwd(FolderSplitPartGroup)
          nome_config = paste("grupo_", g, ".s", sep="")
          sink(nome_config, type = "output")
          
          cat("[General]")          
          cat("\nCompatibility = MLJ08")
          
          cat("\n")
          cat("\n[Data]")
          nome_arquivo_2 = paste("grupo_Tr_", g, ".arff", sep="")
          cat(paste("\nFile = ", nome_arquivo_2, sep=""))
          nome_arquivo_3 = paste("grupo_Vl_", g, ".arff", sep="")
          cat(paste("\nTestSet = ", nome_arquivo_3, sep=""))
          
          cat("\n")
          cat("\n[Attributes]")
          cat("\nReduceMemoryNominalAttrs = yes")
          
          cat("\n")
          cat("\n[Attributes]")
          cat(paste("\nTarget = ", inicio, "-", fim, sep=""))
          cat("\nWeights = 1")
          
          cat("\n")
          cat("\n[Tree]")
          cat("\nHeuristic = VarianceReduction")
          cat("\nFTest = [0.001,0.005,0.01,0.05,0.1,0.125]")
          
          cat("\n")
          cat("\n[Model]")
          cat("\nMinimalWeight = 5.0")
          
          cat("\n")
          cat("\n[Output]")
          cat("\nWritePredictions = {Test}")
          cat("\n")
          sink()
          
          ####################################################################################
          cat("\n\t\t\tExecute CLUS")
          nome_config2 = paste(FolderSplitPartGroup, "/", nome_config, sep="")
          setwd(FolderSplitPartGroup)      
          str = paste("java -jar ", folderUtils, "/Clus.jar ", nome_config2, sep="")
          system(str)
          
          ####################################################################################
          #cat("\nOpen inicioFimRotulos.csv\n")
          targets = data.frame(read.csv("inicioFimRotulos.csv"))
          
          ####################################################################################
          #cat("\nOpen predictions\n")
          namae2 = paste(nome_grupo, ".test.pred.arff", sep="")
          predicoes = data.frame(read.arff(namae2), use_xml = FALSE)
          
          ####################################################################################
          #cat("\nSPLIT PREDICTIS\n")
          if(targets$inicio == targets$fim){
            library("foreign")
            cat("\n\t\t\tOnly one label in this group")
            
            ####################################################################################
            #cat("\nSave Y_true\n")
            setwd(FolderSplitPartGroup)
            classes = data.frame(predicoes[,1])
            names(classes) = colnames(predicoes)[1]
            write.csv(classes, "y_true.csv", row.names = FALSE)
            
            ####################################################################################
            #cat("\nSave Y_true\n")
            rot = paste("Pruned.p.", colnames(predicoes)[1], sep="")
            pred = data.frame(predicoes[,rot])
            names(pred) = colnames(predicoes)[1]
            setwd(FolderSplitPartGroup)
            write.csv(pred, "y_predict.csv", row.names = FALSE)
            
            ####################################################################################
            rotulos = c(colnames(classes))
            n_r = length(rotulos)
            gc()
            
          } else {
            library("foreign")
            ####################################################################################
            cat("\n\t\t\tMore than one label in this group")
            comeco = 1+(targets$fim - targets$inicio)
            
            ####################################################################################
            #cat("\nSave Y_true\n")
            classes = data.frame(predicoes[,1:comeco])
            setwd(FolderSplitPartGroup)
            write.csv(classes, "y_true.csv", row.names = FALSE)
            
            ####################################################################################
            #cat("\nSave Y_true\n")
            rotulos = c(colnames(classes))
            n_r = length(rotulos)
            nomeColuna = c()
            t = 1 
            while(t <= n_r){
              nomeColuna[t] = paste("Pruned.p.", rotulos[t], sep="")
              t = t + 1
              gc()
            }
            pred = data.frame(predicoes[nomeColuna])
            names(pred) = rotulos
            setwd(FolderSplitPartGroup)
            write.csv(pred, "y_predict.csv", row.names = FALSE)
            gc()
          } # FIM DO ELSE
          
          
          nome1 = paste("grupo_Tr_", g, ".arff", sep="")
          nome2 = paste("grupo_Vl_", g, ".arff", sep="")
          nome3 = paste("grupo_Tr_", g, ".csv", sep="")
          nome4 = paste("grupo_Vl_", g, ".csv", sep="")
          nome5 = paste("grupo_", g, ".model", sep="")
          nome6 = paste("grupo_", g, ".s", sep="")
          
          setwd(FolderSplitPartGroup)
          unlink(nome1, recursive = TRUE)
          unlink(nome2, recursive = TRUE)
          unlink(nome3, recursive = TRUE)
          unlink(nome4, recursive = TRUE)
          unlink(nome5, recursive = TRUE)
          #unlink(nome6, recursive = TRUE)
          
          g = g + 1
          gc()
        } 
      }
      
      p = p + 1
      gc()
    } 
    
    gc()
  } 
  
  gc()
  cat("\n##################################################################################################")
  cat("\n# HYBRID PARTITIONS: END                                                                         #")
  cat("\n##################################################################################################")
  cat("\n\n\n\n")
}

##################################################################################################
# Please, any errors, contact us: elainececiliagatto@gmail.com                                   #
# Thank you very much!                                                                           #
##################################################################################################
